var apple = 'red';
console.log("is apple == red |true");
console.log(apple == 'red');
var car = 'purple';
console.log("is car == red |false");
console.log(car == 'red');
var cat = 'small';
console.log("is cat == small |true");
console.log(cat == 'small');
var tiger = 'dangerous';
console.log("is tiger != dangerous |false");
console.log(tiger != 'dangerous');
var game = 'fun';
console.log("is gaem == fun |true");
console.log(game == 'fun');
var sky = 'red';
console.log("is sky == blue |fasle");
console.log(sky == 'blue');
var lion = 'fast';
console.log("is lion != slow |true");
console.log(lion != 'slow');
var psl = 'good';
console.log("is psl == bad |false");
console.log(psl == 'bad');
var baby = 'small';
console.log("is baby == small |true");
console.log(baby == 'small');
var kid = 'funny';
console.log("is kid != funny |false");
console.log(kid != 'funny');
